[tool.black]
line-length = 88
target-version = ['py313']
include = '\.pyi?$'
extend-exclude = ''

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
    "integration",
]