name: CI
on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install img2pdf

      - name: Run tests
        run: python -m pytest

      - name: Create PDF
        run: find ./dist/screenshots -name "*.png" | xargs img2pdf -o screenshot-report.pdf
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: |
            screenshot-report.pdf
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: pip install -r requirements.txt
      - run: python -m ruff check
