name: CI
on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python -m pytest -k "test_screenshots"

      - name: test thing
        run: |
          ls main-site/e2e/screenshots

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: |
            main-site/e2e/screenshots/**/*.png

      - name: Create summary
        run: echo ‘### Hello world! :rocket:’ >> $GITHUB_STEP_SUMMARY
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: pip install -r requirements.txt
      - run: python -m ruff check
