name: CI
on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python -m pytest

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: |
            main-site/e2e/screenshots/*.png
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: pip install -r requirements.txt
      - run: python -m ruff check
